import React from "react";

const PolicyPage = () => {
  return (
    <div className="min-h-screen bg-gray-50 px-4 py-10">
      <div className="mx-auto max-w-4xl rounded-2xl bg-white p-6 shadow-sm sm:p-10">
        <h1 className="mb-6 text-2xl font-bold text-gray-900 sm:text-3xl">
          Application Policy
        </h1>

        <p className="mb-8 text-sm text-gray-500">
          Privacy Policy & Medical Disclaimer <br />
          <span className="italic">Last Updated: January 23, 2026</span>
        </p>

        <section className="space-y-6 text-gray-700 leading-relaxed">
          <p>
            By using <strong>SkinGlanceCare</strong> ("the Service"), you
            explicitly agree to the terms outlined below. If you do not agree,
            you must cease use of the Service immediately.
          </p>

          <div>
            <h2 className="mb-2 text-lg font-semibold text-gray-900">
              1. Absolute Medical Disclaimer
            </h2>
            <p>
              SkinGlanceCare is an AI-based informational tool. It is{" "}
              <strong>not</strong> a medical device and does{" "}
              <strong>not</strong> provide medical advice, diagnosis, or
              treatment. The results generated by the model are based on
              statistical patterns and may be incorrect, incomplete, or
              misleading.
            </p>
            <p className="mt-2">
              The Service is not a substitute for professional clinical advice
              from a board-certified dermatologist. Never disregard professional
              medical advice or delay seeking it because of information obtained
              from this Service.
            </p>
          </div>

          <div>
            <h2 className="mb-2 text-lg font-semibold text-gray-900">
              2. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, SkinGlanceCare, its
              owners, and developers shall not be liable for any direct,
              indirect, incidental, or consequential damages resulting from the
              use of the Service.
            </p>
            <ul className="mt-2 list-disc pl-5">
              <li>Reliance on AI-generated analysis</li>
              <li>Errors, glitches, or inaccuracies in the model</li>
              <li>Delay in seeking professional medical assistance</li>
            </ul>
          </div>

          <div>
            <h2 className="mb-2 text-lg font-semibold text-gray-900">
              3. Data Processing & Consent
            </h2>
            <p>By uploading an image, you consent to:</p>
            <ul className="mt-2 list-disc pl-5">
              <li>Processing images using neural networks</li>
              <li>Storing anonymized images to improve model accuracy</li>
              <li>
                Uploading only non-identifiable images (no faces, tattoos, or
                unique birthmarks)
              </li>
            </ul>
          </div>

          <div>
            <h2 className="mb-2 text-lg font-semibold text-gray-900">
              4. Data Security
            </h2>
            <p>
              While industry-standard security measures are applied, no method
              of transmission over the Internet is completely secure. By using
              the Service, you acknowledge and accept these risks.
            </p>
          </div>

          <div>
            <h2 className="mb-2 text-lg font-semibold text-gray-900">
              5. "As Is" Warranty
            </h2>
            <p>
              The Service is provided on an <strong>"AS IS"</strong> and{" "}
              <strong>"AS AVAILABLE"</strong> basis without warranties of any
              kind, either expressed or implied.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
};

export default PolicyPage;
